### ISSUE TITLE
Nest can't resolve dependencies of the SocketIoEventLoader (DiscoveryService, MetadataScanner, ?, SOCKET_IO_CLIENT, SOCKET_OPTIONS).

### ISSUE THREAD

**Issue by WildEgor** [danocmx/nestjs-socket.io-client#1]
Use your example and got error:

ERROR [ExceptionHandler] Nest can't resolve dependencies of the SocketIoEventLoader (DiscoveryService, MetadataScanner, ?, SOCKET_IO_CLIENT, SOCKET_OPTIONS). Please make sure that the argument Reflector at index [2] is available in the SocketIoClientModule context.

Potential solutions:
- If Reflector is a provider, is it part of the current SocketIoClientModule?
- If Reflector is exported from a separate @Module, is that module imported within SocketIoClientModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })

**Comment by ruslanguns** [comment]
@WildEgor just found the same issue and sent a PR for fixing this behaviour! hopefully it gets merged soon by the maintainer

**Comment by danocmx** [comment]
Fixed in version 1.0.6, thanks @ruslanguns

**Comment by wolfgang555** [comment]
is this issue fixed?

```log
 ERROR [ExceptionHandler] Nest can't resolve dependencies of the SocketIoEventLoader (DiscoveryService, MetadataScanner, ?, SOCKET_IO_CLIENT, SOCKET_OPTIONS). Please make sure that the argument Reflector at index [2] is available in the SocketIoClientModule context.

Potential solutions:
- If Reflector is a provider, is it part of the current SocketIoClientModule?
- If Reflector is exported from a separate @Module, is that module imported within SocketIoClientModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })

```

**Comment by wolfgang555** [comment]
```log
        "nestjs-socket.io-client": "^1.0.6",
```
